version: '2'
services:
  api:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 5000:5000
    command: python3 manage.py run -h 0.0.0.0

  pytest:
    extends: api
    command: python -m pytest -vv
